---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dso-install-manager-wave-2
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  ignoreApplicationDifferences:
    - jqPathExpressions:
        - .spec.source.plugin.env[] | select(.name == "HELM_VALUES").value
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/mathieulaude/appset-syncwave.git
              revision: main
              files:
                - path: "./gitops/envs/*/*.json"
              requeueAfterSeconds: 10
          - list:
              elementsYaml: "{{ .apps | toJson }}"
            selector:
              matchExpressions:
                - key: enabled
                  operator: In
                  values:
                    - "true"
                - key: syncWave
                  operator: In
                  values: ["30"]
  template:
    metadata:
      name: "test-{{.prefix}}{{.app}}"
      annotations:
        argocd.argoproj.io/compare-options: ServerSideDiff=true
        argocd.argoproj.io/sync-wave: "{{.syncWave}}"
      labels:
        platform.env: "{{.env}}"
        platform.provider: "{{.provider}}"
        platform.region: "{{.region}}"
        sync-wave: "{{.syncWave}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      revisionHistoryLimit: 3
      source:
        repoURL: https://github.com/mathieulaude/helm-example.git
        path: charts/hello-world
        targetRevision: main
      destination:
        name: "in-cluster"
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
        #  selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
  syncPolicy:
    preserveResourcesOnDeletion: true
    # automated:
    #   selfHeal: true
